---
sensu_package_name: sensu
sensu_server_service_name: sensu-server
sensu_api_service_name: sensu-api
sensu_client_service_name: sensu-client

sensu_config_path: /etc/sensu/conf.d

sensu_owner: sensu
sensu_group: sensu

sensu_rabbitmq_server: >
  {{ hostvars[groups.rabbit_hosts.0].ansible_default_ipv4.address}}
sensu_rabbitmq_port: 5672
sensu_rabbitmq_user: sensu
sensu_rabbitmq_password: sensu
sensu_rabbitmq_vhost: /sensu
