---
sensu_api_bind: 0.0.0.0
sensu_api_port: 4567
sensu_api_server: localhost

sensu_redis_server: 127.0.0.1
sensu_redis_port: '{{ redis_listen_port }}'
sensu_redis_password: "{{ redis_password }}"

sensu_enabled_oschecks:
  - check-ceilometer_api
  - check-ceph_df
  - check-ceph_health
  - check-cinder_api
  - check-cinder_volume
  - check-glance_api
  - check-keystone_api
  - check-neutron_api
  - check-nova_api
  - check-nova_instance

oscheck_default_username: admin
oscheck_default_password: pass
oscheck_default_project_name: admin
oscheck_default_auth_url: http://controller:5000/v2.0
oscheck_default_region_name: RegionOne

oscheck_subscribers_ceilometer_api: 'overcloud-ceilometer-api'
oscheck_subscribers_ceph: 'overcloud-ceph-client'
oscheck_subscribers_cinder_api: 'overcloud-cinder-api'
oscheck_subscribers_cinder_volume: 'overcloud-cinder-volume'
oscheck_subscribers_glance_api: 'overcloud-glance-api'
oscheck_subscribers_neutron_api: 'overcloud-neutron-server'
oscheck_subscribers_nova_api: 'overcloud-nova-api'
oscheck_subscribers_nova_instance: 'overcloud-nova-compute'
oscheck_subscribers_keystone_api: 'overcloud-keystone'
